### ISSUE TITLE
bicycle=use_sidepath

### ISSUE THREAD

**Issue by ghost** [Project-OSRM/osrm-backend#1171]
Is it possible to include highway=use_sidepath
http://wiki.openstreetmap.org/wiki/Tag:bicycle%3Duse_sidepath for proritizing routes for bicycles?

Is it possible to manually proritize some way in lua? Like i dont like cyclying on secondary and primary even it is permited and would choos highway=path bicycle=designated instead.

The use_sidepath is not consideed right now, i have just checked with v0.4.2b osrm.

**Comment by daniel-j-h** [comment]
More then 36k tags now @emiltin want to include this for bike routing? :)

**Comment by emiltin** [comment]
yes, working on refactoring the bike profile anyways (it's a bit more complicated than the car profile though..)

**Comment by jdhoek** [comment]
The tag `bicycle=use_sidepath` is currently taken to mean that routers should not use roads tagged with it for bicycles at all, and implies that a parallel road suitable for cyclists is drawn on the map and available for routing.

This is fixed in #5622 .

Should there be any exceptions to this rule, please update the documentation on the OpenStreetMap wiki.

**Comment by fqdb** [comment]
It still appears to route over roads tagged with use_sidepath, or is the OSM website still using an old OSRM version?

https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=52.29963%2C4.91194%3B52.30357%2C4.92012#map=17/52.30115/4.91532

**Comment by datendelphin** [comment]
The current backend server for osm.org has its separate profile repository: https://github.com/fossgis-routing-server/cbf-routing-profiles sorry for the confusion

**Comment by jdhoek** [comment]
@datendelphin openstreetmap.org says it uses 'Bicycle/Car/Foot OSRM', so that is indeed rather confusing. Are you tracking upstream (this repo) for fixes?

Are the changes made in that repo not desirable upstream (i.e., here)?

**Comment by datendelphin** [comment]
osm.org does show you a link to the about page where all is explained and linked.
It would be great if someone would go through both profiles and pick the good sides from both I think. They are not so far apart.
