### ISSUE TITLE
Spotting unfound routes between points when using table

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-backend#1301]
Hi

I use table requests for computing matrices. I observed that in the case of two locs for wich no route can be found (status 207 for viaroute request) the resulting travel time is set to an arbitrary (?) big value.

For example:
viaroute?loc=47.347575,4.993436&loc=47.318732,5.068607
gives a 207 status and when included in a table request, travel times to the second loc are all set to 3579140 seconds (same value on another example).

This behaviour is not a problem for me but I can't avoid those cases (due to local topologic specificities and the fact that I use random locs) so I would like to be able to filter them when I get the matrix.

Is there a way you would suggest for spotting those cases using the "unusually" high travel times ? Relying on the specific 3579140 sec value seems to be a poor hack...

Thanks for all the work, especially the table feature wich is great!

**Comment by TheMarex** [comment]
This should be fixed. The distance table was broken in the develop branch. If the route is not found, it should return ```INT_MAX = 2^32 - 1```.

**Comment by jcoupey** [comment]
Thanks for the feedback.

I've just re-compiled the code from the master branch and it doesn't fix the problem. Does your comment mean I should compile from the develop branch ?

**Comment by DennisOSRM** [comment]
@jcoupey yes, development happens in the develop branch

**Comment by jcoupey** [comment]
> development happens in the develop branch

Sounds like a good practice... ;-) 
I just didn't know if the relevant changes had been merged to master yet.

After recompilation, osrm-extract and osrm-prepare, all is now fine with the table requests. I do get the expected `INT_MAX` value when no route is found.

Thanks again.
