### ISSUE TITLE
autoroute suggested for reaching residential house protected by private access gate

### ISSUE THREAD

**Issue by paolobenve** [Project-OSRM/osrm-backend#3616]
See:

http://www.openstreetmap.org/directions?engine=osrm_car&route=44.42860%2C8.81110%3B44.43065%2C8.80909#map=15/44.4272/8.7884

there is a very simple route between start and destination, but probably the enging evaluates that the autoroute is closer to destination than the gate which must be crossed in order to reach destination.

Autoroutes cannot be exited but in their gates

**Comment by danpat** [comment]
@paolobenve Yes, the problem is that the start coordinate is closest to the autoroute.

The difficulty here is that it is valid to ask for a route starting on an autoroute - imagine if you're in your car, and you use your phone to ask OSRM for directions from your current position.

This is made more difficult by the private gated area.  You can see it on the OSRM debug map here:

http://map.project-osrm.org/debug/#16.64/44.43027/8.80954
![screen shot 2017-01-26 at 3 41 37 pm](https://cloud.githubusercontent.com/assets/1892250/22355166/f518b330-e3dd-11e6-8bad-6af597df70c2.png)

The area highlighted in pink is not "snappable" unless both start/end coordinates are close to it.  This is by design.

Unless somebody has a suggestion for what we should actually change here, I think this ticket should be closed.

**Comment by danpat** [comment]
Note that this upcoming pull request https://github.com/Project-OSRM/osrm-backend/pull/2399 will change this behaviour somewhat - private areas *should* become routable when you drop a marker close to them.

**Comment by emiltin** [comment]
what about a possibility to pass not only the bearing for the start point, but also a speed? that would be a way to determine whether you're on a highway or not

**Comment by paolobenve** [comment]
@danpat, in the link I put it's not the start, but the end that is in an autoroute. It makes no sense that osrm leave the user on an autoroute when he/she want to reach a house.

mapzen, actually, brings the user inside the private area, and I think this is the correct behaviour, OSRM must not worry about the gate, if the use wants to reach the house inside the gate it means he/she knows how to enter the private area.

I wouldn't close this ticket

**Comment by MoKob** [comment]
This will be solved, when #77 finally lands. Our problem here is that we cannot route into gated areas, since we cannot distinguish between routing into and routing through a gated area.
Consider a military basis for example:

If you want to get to the center of it, you will probably have the right to do so. If not, we will show you how to get there and you will get to a checkpoint and realise that your destination was a bad idea.
If you are a normal driver that wants to go from one side of the basis (outside) to the other side, providing you a route through the base is probably not a good idea.
We require #77 to be able to distinguish between both situations.
Until then, it is OK to keep this open as a feature request to handle gates correctly.

What we need to do:

- [ ] get #77 merged
- [ ] handle gates
    - [ ] don't block access in the engine for gates ([here](https://github.com/Project-OSRM/osrm-backend/blob/c7640903c36a3ea7dbe062e8d98e5e1284507501/src/extractor/guidance/intersection_generator.cpp#L240), [and here](https://github.com/Project-OSRM/osrm-backend/blob/c7640903c36a3ea7dbe062e8d98e5e1284507501/src/extractor/guidance/intersection_generator.cpp#L274))
    - [ ] update profiles to add high time penalty on gates

**Comment by MoKob** [comment]
Related: https://github.com/Project-OSRM/osrm-backend/issues/156

**Comment by karenzshea** [comment]
https://github.com/Project-OSRM/osrm-backend/pull/3721 that will be part of the 5.6 release has a fix for this that allows routing into typically restricted ways if they are provided as start or endpoints .

**Comment by daniel-j-h** [comment]
@karenzshea implemented this in https://github.com/Project-OSRM/osrm-backend/pull/3721 for the 5.6 release.

![next](https://cloud.githubusercontent.com/assets/527241/23166378/baaaf6a0-f840-11e6-9caf-d7028e1f854a.png)

Closing here.

**Comment by daniel-j-h** [comment]
Reopening - we're still stopping at the gate. @karenzshea is there a reason we simple don't handle _all_ gated areas instead of just `gate=private`?

**Comment by karenzshea** [comment]
The route doesn't work properly on OSM and on the demo server because the demo server has not properly processed the planet since the relevant changes have been made in OSRM. Let's hold on closing this until this issue has been demonstrated to work outside of OSRM tests :)

**Comment by daniel-j-h** [comment]
Yep the issue was the demo server not having cycled in the new code and data. This is fixed now!

**Comment by paolobenve** [comment]
thank you guys, something has got better!

but there's still a problem with autoroute, see http://www.openstreetmap.org/directions?engine=osrm_car&route=44.43077%2C8.80858%3B44.43088%2C8.80853#map=14/44.4274/8.7956: start and end point are outside the autoroute, but osrm still uses it!

Or is it related to this other weird behaviour: http://www.openstreetmap.org/directions?engine=osrm_car&route=44.42988%2C8.80924%3B44.43017%2C8.80893#map=19/44.42996/8.80915 ? route doesn't continue on a way with surface=compacted

**Comment by TheMarex** [comment]
@paolobenve that road is literally 15 minutes old and not included in our routing graph yet. http://www.openstreetmap.org/way/477341231/history It will take about 48 hours until it will be reflected on our demo server.

**Comment by paolobenve** [comment]
I didn't modify anything in openstreetmap...

@TheMarex Perhaps I didn't understand what do you mean in "that road is literally 15 minutes old and not included in our routing graph yet".

**Comment by TheMarex** [comment]
@paolobenve there is nothing else to snap to but the motorway. The way the you placed the markers on was 15 minutes old at the time of posting, so not included in the routing graph.

If you look closely in our frontend http://map.project-osrm.org/?z=18&center=44.430238%2C8.808967&loc=44.430765%2C8.808578&loc=44.430892%2C8.808503&hl=en&alt=0 you will see those dotted gray lines which indicate the distance to the point where it actually snapped to.

**Comment by paolobenve** [comment]
"there is nothing else to snap to but the motorway": no, the start and end point in http://www.openstreetmap.org/directions?engine=osrm_car&route=44.43077%2C8.80858%3B44.43088%2C8.80853#map=14/44.4274/8.7956 are on a surface=compacted road, I expect that osrm makes me move on that road. Anyway, here in Italy nobody can enter a highway but through the regular gates, it doesn't make sense that osrm snaps to the highway a start/end point outside it

My question is: why in http://map.project-osrm.org/?z=18&center=44.429894%2C8.810161&loc=44.430516%2C8.808675&loc=44.429892%2C8.809190&hl=en&alt=0 the osrm doesn't suggest the more obvious route, i.e. the surface=compacted road? It seems a bug to me

**Comment by daniel-j-h** [comment]
Because the way in question is a service road and osrm does not include them in the road network by default

http://www.openstreetmap.org/way/477341231

You can take a look at the debug map (demo server, bottom left, see icons)

http://map.project-osrm.org/debug/#18/44.43023/8.80958

**Comment by paolobenve** [comment]
it's ok that service roads are not included in routes by default: normal roads are to be preferred anyway

But it's the same situations as with gates: if start or end point in inside a gate, the produced route must cross it. Equally, if the start or end point in on a service road, the route should include the part of the service road which connects to the normal road

**Comment by paolobenve** [comment]
In the case the start/end point is on a service road, I think that a better snapping would be at the beginning of the service road, it would be surely better that to a "near" point on a normal road: it's not correct to suppose that the "near" point is reachable from start/end point
