### ISSUE TITLE
Route pedestrians over highway=platform

### ISSUE THREAD

**Issue by ghost** [Project-OSRM/osrm-backend#5410]
Please allow pedestrians to be routed over `highway=platform`. (This tag should be treated the same as `highway=footway`.) Currently, they are diverted onto the street, see e.g. [here](https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=46.94396%2C7.44898%3B46.94285%2C7.44841#map=18/46.94343/7.44866).

**Comment by AllroadsNL** [comment]
This is important!

I noticed the same problem, for small walk through sidewalk,where a part is higher, this is the platform. On the publiic_transport=platform area=yes is the highway=platform (routing) line. Routing line with tactile_paving, line drawn on this tactile_paving pavingstones line. The save walk route.
At a highway platform you can expect people waiting for the bus. 
Because it is so small, there is no footway beside the platform.

Not routing over it can give a huge detour on foot, or with a wheelchair, this must be avoided.

Like the example above.
On the country side, road with sidewalk drawn in. less roads, this give huge detour.
Also when there is foot=no on the road. Or foot=use_sitepath. (if use_sidepath is used in routing)

**Comment by kaligrafy** [comment]
The problem seems to be that the data imported when extracting data (the original osm or pbf file) did not include railway=platform ways. Use this query on overpass turbo to include railway platforms and other needed data (piers and leisure tracks):

```[timeout:100]
[out:xml]
;
(
  way["highway"]({{bbox}});
  node(w);
  node(r);
  way(r);
  way["railway"="platform"]({{bbox}});
  node(w);
  node(r);
  way(r);
  way["man_made"="pier"]({{bbox}});
  node(w);
  node(r);
  way(r);
  way["leisure"="track"]({{bbox}});
  node(w);
  node(r);
  way(r);
);
out meta;
>;
```

**Comment by 16NoCo** [comment]
Any update on this?

As the problem appears on openstreetmap.org when routing with OSRM, should we ask _them_ to perform what @kaligrafy suggests?  
Also, this issue appears on the official OSRM demo website, so if the issue isn't fixed in the code, the above fix should also be performed there.

**Comment by AllroadsNL** [comment]
It is still a problem.

Way highway=plaform does not route.

**Comment by kaligrafy** [comment]
Another hack is to add the tag highway=footway on platforms, which is in my opinon, 100% valid.

**Comment by Woazboat** [comment]
This is about `highway=platform`, so `highway=footway` _cannot_ be added

**Comment by nilsnolde** [comment]
While I agree with @kaligrafy (and I guess he means _change_ not _add_), the [OSM wiki](https://wiki.openstreetmap.org/wiki/Public_transport) suggests to map `highway=platform` for line features. So we should add it (also talking about us over in Valhalla, not supporting it either yet). Should be really quick & easy for both to implement. I'll fix it for Valhalla soon, can take a quick stab at OSRM too.

**Comment by kaligrafy** [comment]
I agree this should be fixed anyway.

**Comment by AllroadsNL** [comment]
It is not solved, did a test today on the Openstreetmap webpage.

**Comment by kaligrafy** [comment]
Not yet fixed. Keep open

**Comment by DennisOSRM** [comment]
Should be a matter of adding this line to the foot profile, and then some tests covering it:

```
diff --git a/profiles/foot.lua b/profiles/foot.lua
index 1b16e092c..fa5f8b663 100644
--- a/profiles/foot.lua
+++ b/profiles/foot.lua
@@ -90,6 +90,7 @@ function setup()
         path            = walking_speed,
         steps           = walking_speed,
         pedestrian      = walking_speed,
+        platform        = walking_speed,
         footway         = walking_speed,
         pier            = walking_speed,
       },
```
